"use client";
import {useCallback,useEffect,useRef,useState,type CSSProperties,type ReactNode} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import * as sfx from "@/lib/sfx";
import {characters,profiles,leaning,sampleCouncil,sampleInput,type Character,type StoryInput,type StoryResult} from "@/lib/story";

type Page="cover"|"welcome"|"question"|"gathering"|"council"|"willow"|"roots"|"keepsake"|"safety";
const chapters:Partial<Record<Page,string>>={welcome:"The invitation",question:"I · Your crossroads",gathering:"The grove is listening",council:"II · A little perspective",willow:"III · What matters",roots:"IV · Where the roots lead",keepsake:"V · Something to carry",safety:"A moment of care"};
const order:Page[]=["cover","welcome","question","gathering","council","willow","roots","keepsake","safety"];
const TURN_MS=1150,STRIPS=8;
const image=(id:Character,speaking=false)=>"/art/"+id+(speaking?"-speaking":"")+".png";
function Portrait({id,speaking=false,className=""}:{id:Character;speaking?:boolean;className?:string}){
 return <div className={"portrait "+id+" "+className+(speaking?" speaking":"")}><img src={image(id)} alt={profiles[id].name} className={speaking?"rest-pose faded":"rest-pose"}/><img src={image(id,true)} alt="" aria-hidden className={speaking?"speak-pose visible":"speak-pose"}/>{id==="willow"&&<span className="willow-glow" aria-hidden/>}</div>;
}
function Ink({text}:{text:string}){const [n,setN]=useState(0);useEffect(()=>{if(matchMedia("(prefers-reduced-motion: reduce)").matches){setN(text.length);return;}setN(0);const timer=setInterval(()=>setN(v=>{if(v>=text.length)clearInterval(timer);return Math.min(v+4,text.length);}),24);return ()=>clearInterval(timer)},[text]);return <p className="advice"><span className="sr-only">{text}</span><span aria-hidden>{text.slice(0,n)}<span className="unwritten">{text.slice(n)}</span></span></p>;}
function Roots({story,input}:{story:StoryResult;input:StoryInput}){
const votes=leaning(story.council);return <div className="roots-spread">
<span className="chapter-label">Three ways of seeing</span><h2>Follow the threads.</h2><p className="root-intro">{votes.winner==="unsure"?"The grove leaves room for uncertainty. Both paths remain open.":"Their perspectives meet here. Notice whether that feels right to you."}</p>
<div className="root-map"><div className="root-guides">{characters.map(id=><div key={id}><Portrait id={id}/><span>{profiles[id].name}</span></div>)}</div>
<svg viewBox="0 0 1000 330" className="root-lines" role="img" aria-label={"Animated paths connect each character to their preferred option. "+votes.a+" lean toward the first option; "+votes.b+" toward the second."}>
<defs><filter id="root-glow"><feGaussianBlur stdDeviation="3"/></filter><radialGradient id="bloom"><stop stopColor="#fff2b0"/><stop offset=".3" stopColor="#ffcf68" stopOpacity=".8"/><stop offset="1" stopColor="#f4a943" stopOpacity="0"/></radialGradient></defs>
{characters.map((id,i)=>{const lean=story.council[id].lean;const x=170+i*330;const end=lean==="A"?230:lean==="B"?770:500;const d="M"+x+" 4 C"+x+" 100, "+(500+(i-1)*55)+" 110, 500 172 C500 232, "+end+" 214, "+end+" 300";return <g key={id} style={{"--root-delay":i*.8+"s"} as CSSProperties}><path d={d} className="root-halo" stroke={profiles[id].color}/><path d={d} className="root-thread" stroke={profiles[id].color} pathLength="1"/><path d={d} className="root-spark" pathLength="1"/></g>})}
{votes.winner!=="unsure"&&<g className="root-bloom" transform={"translate("+(votes.winner==="A"?230:770)+",300)"}><circle r="65" fill="url(#bloom)"/><circle r="12" fill="#ffe6a1"/><path d="M-22 0Q0-45 22 0Q0 45-22 0M0-22Q45 0 0 22Q-45 0 0-22" fill="#ffeab5" opacity=".7"/></g>}
</svg><div className="root-options"><div className={votes.winner==="A"?"chosen":""}><span>PATH ONE</span><h3>{input.optionA}</h3><p>{votes.a} of 3 perspectives</p></div><div className={votes.winner==="B"?"chosen":""}><span>PATH TWO</span><h3>{input.optionB}</h3><p>{votes.b} of 3 perspectives</p></div></div>
</div><p className="root-disclaimer">Three perspectives from one AI, not a prediction or a verdict.</p></div>;
}
async function loadImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=src;});}
async function downloadKeepsake(input:StoryInput,story:StoryResult){
const canvas=document.createElement("canvas");canvas.width=1400;canvas.height=5000;const c=canvas.getContext("2d")!;
const paper=await loadImage("/art/cream-watercolor-paper-2048.png");c.fillStyle=c.createPattern(paper,"repeat")!;c.fillRect(0,0,1400,5000);
let y=150;c.fillStyle="#2c4942";c.textAlign="center";c.font="24px Georgia";c.fillText("O R A C L E   G R O V E",700,y);y+=90;c.font="64px Georgia";c.fillText("A little clarity to carry",700,y);y+=70;
function lines(text:string,width:number,font:string,spacing:number){c.font=font;const words=text.split(/\s+/);let line="";const result:string[]=[];for(const word of words){if(c.measureText(line+" "+word).width>width&&line){result.push(line);line=word;}else line+=(line?" ":"")+word;}if(line)result.push(line);for(const l of result){c.fillText(l,700,y);y+=spacing;}}
c.fillStyle="#534939";lines(input.question.length>360?input.question.slice(0,357)+"...":input.question,1120,"italic 30px Georgia",42);y+=45;
for(const id of characters){const img=await loadImage(image(id));c.globalCompositeOperation="multiply";const h=175,w=img.width/img.height*h;c.drawImage(img,700-w/2,y,w,h);c.globalCompositeOperation="source-over";y+=207;c.fillStyle="#234843";c.font="32px Georgia";c.fillText(profiles[id].name,700,y);y+=42;c.fillStyle="#625442";lines(story.council[id].keepsake,1080,"26px Georgia",35);y+=35;}
y+=15;c.fillStyle="#2c4942";c.font="22px Georgia";c.fillText("ONE SMALL NEXT STEP",700,y);y+=43;c.fillStyle="#625442";lines(story.council.next_step,1040,"26px Georgia",35);
y+=45;const seal=await loadImage("/art/wax-seal.png");c.globalCompositeOperation="multiply";c.drawImage(seal,630,y,140,140);c.globalCompositeOperation="source-over";y+=190;c.fillStyle="#28433e";c.font="italic 34px Georgia";c.fillText("This choice is yours.",700,y);
const height=Math.ceil(y+100);c.strokeStyle="#af9661";c.lineWidth=2;c.strokeRect(55,55,1290,height-110);const output=document.createElement("canvas");output.width=1400;output.height=height;output.getContext("2d")!.drawImage(canvas,0,0);
const a=document.createElement("a");a.download="oracle-grove-keepsake.png";a.href=output.toDataURL("image/png");a.click();return a.href;
}
export default function Storybook(){
const [page,setPage]=useState<Page>("cover"),[turning,setTurning]=useState(false),[opening,setOpening]=useState(false),[turnDir,setTurnDir]=useState<"forward"|"back">("forward"),[turnFrom,setTurnFrom]=useState<Page|null>(null),[turnTo,setTurnTo]=useState<Page|null>(null),[effects,setEffects]=useState(true),[music,setMusic]=useState(true),[leafW,setLeafW]=useState(0);
const [compact,setCompact]=useState(false),effectsRef=useRef(true),lightRef=useRef<HTMLDivElement|null>(null),lightRaf=useRef(0),bookRef=useRef<HTMLElement|null>(null);
const [input,setInput]=useState<StoryInput>({question:"",optionA:"",optionB:""}),[story,setStory]=useState<StoryResult|null>(null);
const [error,setError]=useState(""),[sound,setSound]=useState(false),[playing,setPlaying]=useState<Character|null>(null),[loadingVoice,setLoadingVoice]=useState<Character|null>(null),[voiceError,setVoiceError]=useState(""),[generalSafety,setGeneralSafety]=useState(false),[saving,setSaving]=useState(false),[keepsakeUrl,setKeepsakeUrl]=useState("");
const stageRef=useRef(page),audioRef=useRef<HTMLAudioElement|null>(null),audioCache=useRef<Partial<Record<Character,string>>>({}),audioJobs=useRef<Partial<Record<Character,Promise<string>>>>({}),timers=useRef<ReturnType<typeof setTimeout>[]>([]),headingRef=useRef<HTMLDivElement>(null),requestRef=useRef<AbortController|null>(null),playVersion=useRef(0),storyVersion=useRef(0);
stageRef.current=page;
const stopAudio=useCallback(()=>{playVersion.current++;audioRef.current?.pause();audioRef.current=null;setPlaying(null);setLoadingVoice(null);},[]);
useEffect(()=>{effectsRef.current=effects;},[effects]);
useEffect(()=>{sfx.duckAmbient(!!playing);},[playing]);
useEffect(()=>()=>sfx.stopAmbient(),[]);
const startTurn=useCallback((next:Page,cancelled?:()=>boolean)=>{const from=stageRef.current;stopAudio();setVoiceError("");const dir=order.indexOf(next)<order.indexOf(from)?"back":"forward";setCompact(matchMedia("(max-width:760px)").matches);setLeafW((bookRef.current?.clientWidth||0)/2);setTurnDir(dir);setTurnFrom(from);setTurnTo(next);setTurning(true);if(effectsRef.current)sfx.turn(dir);timers.current.push(setTimeout(()=>{if(cancelled?.())return;setPage(next);headingRef.current?.focus({preventScroll:true});},TURN_MS*.5),setTimeout(()=>{setTurning(false);setTurnFrom(null);setTurnTo(null);},TURN_MS));},[stopAudio]);
const go=useCallback((next:Page)=>{if(turning||stageRef.current===next)return;startTurn(next);},[turning,startTurn]);
useEffect(()=>()=>{requestRef.current?.abort();timers.current.forEach(clearTimeout);audioRef.current?.pause();Object.values(audioCache.current).forEach(u=>u&&URL.revokeObjectURL(u));},[]);
useEffect(()=>{const media=matchMedia("(prefers-reduced-motion: reduce)");const v=document.querySelector<HTMLVideoElement>(".grove-film");if(media.matches)v?.pause();},[]);
function clearAudio(){setKeepsakeUrl("");storyVersion.current++;stopAudio();for(const u of Object.values(audioCache.current))if(u?.startsWith("blob:"))URL.revokeObjectURL(u);audioCache.current={};audioJobs.current={};}
async function getVoice(id:Character,result:StoryResult):Promise<string>{
if(audioCache.current[id])return audioCache.current[id]!;
if(result.sample){const url="/audio/sample-"+id+".mp3";audioCache.current[id]=url;return url;}
if(audioJobs.current[id])return audioJobs.current[id]!;
const epoch=storyVersion.current;const job=(async()=>{const r=await fetch("/api/voice",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticket:result.tickets[id]})});if(!r.ok){const d=await r.json() as {error?:string};throw new Error(d.error||"Narration is unavailable.");}const url=URL.createObjectURL(await r.blob());if(epoch!==storyVersion.current){URL.revokeObjectURL(url);throw new Error("Narration cancelled");}audioCache.current[id]=url;return url;})();audioJobs.current[id]=job;
try{return await job;}finally{if(audioJobs.current[id]===job)delete audioJobs.current[id];}
}
const play=useCallback(async(id:Character,result:StoryResult,chain=false)=>{
stopAudio();const version=playVersion.current;setVoiceError("");setLoadingVoice(id);
try{const url=await getVoice(id,result);if(version!==playVersion.current)return;
const audio=new Audio(url);audioRef.current=audio;audio.onended=()=>{setPlaying(null);if(chain&&id==="quill"&&stageRef.current==="council")void play("ember",result,false);};audio.onerror=()=>{setPlaying(null);setVoiceError("The voice couldn't play. You can still read every word.");};
await audio.play();setLoadingVoice(null);setPlaying(id);
}catch(e){if(version===playVersion.current){setLoadingVoice(null);setPlaying(null);setVoiceError(e instanceof Error?e.message:"Narration isn't available right now.");}}
},[stopAudio]);
useEffect(()=>{if(!story||!sound||turning)return;const id=page==="council"?"quill":page==="willow"?"willow":null;if(id)void play(id,story,true);},[page,story,sound,turning,play]);
async function ask(custom?:StoryInput){const value=custom||input;if(value.question.trim().length<8||value.optionA.trim().length<2||value.optionB.trim().length<2||value.optionA.trim().toLowerCase()===value.optionB.trim().toLowerCase()){setError("Tell us a little more, and give the grove two different options.");return;}
clearAudio();setStory(null);setError("");setGeneralSafety(false);setInput(value);go("gathering");requestRef.current?.abort();const controller=new AbortController();requestRef.current=controller;
try{const r=await fetch("/api/council",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(value),signal:controller.signal});const data=await r.json() as StoryResult & {safety?:boolean;general?:boolean;error?:string};if(controller.signal.aborted)return;
if(!r.ok)throw new Error(data.error||"The grove couldn't answer. Please try again.");
const next=data.safety?"safety":"council";if(data.safety)setGeneralSafety(!!data.general);else setStory(data);
timers.current.push(setTimeout(()=>{if(controller.signal.aborted)return;startTurn(next,()=>controller.signal.aborted);},1100));
}catch(e){if(controller.signal.aborted)return;setError(e instanceof Error?e.message:"The grove couldn't connect. Please try again.");timers.current.push(setTimeout(()=>{setPage("question");setTurning(false);},1000));}}
function demo(){clearAudio();setInput(sampleInput);setStory({council:sampleCouncil,tickets:{},sample:true});setError("");go("council");}
function restart(){requestRef.current?.abort();clearAudio();setError("");setInput({question:"",optionA:"",optionB:""});setStory(null);go("question");}
function soundToggle(){setSound(v=>!v);if(sound)stopAudio();else if(effects)sfx.chime();}
function musicToggle(){if(music)sfx.stopAmbient();else sfx.startAmbient();setMusic(v=>!v);}
function effectsToggle(){setEffects(v=>!v);if(!effects)sfx.chime();}
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:"stage_grove_question",title:"Prepare a question for the grove",description:"Fill the visible question form without submitting it or calling AI services.",inputSchema:{type:"object",properties:{question:{type:"string"},optionA:{type:"string"},optionB:{type:"string"}},required:["question","optionA","optionB"],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(v:StoryInput)=>{if(!v||typeof v.question!=="string"||typeof v.optionA!=="string"||typeof v.optionB!=="string"||v.question.length>1800||v.optionA.length>180||v.optionB.length>180)throw new Error("Invalid question fields");setInput(v);setPage("question");await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return {page:"question",submitted:false};}},{signal:lifecycle.signal})).catch(()=>{});return ()=>lifecycle.abort();},[]);
function Listen({id}:{id:Character}){return <Button variant="ghost" className="listen-button" disabled={loadingVoice===id} onClick={()=>{if(playing===id)stopAudio();else if(story)void play(id,story);}} aria-label={(playing===id?"Pause ":"Listen to ")+profiles[id].name}>{loadingVoice===id?"Preparing voice…":playing===id?"Ⅱ Pause":"◖ Listen"}</Button>}
function AdvicePage({id}:{id:Character}){return <><span className="chapter-label">{profiles[id].role}</span><div className="adviser-heading"><h2>{profiles[id].name}</h2>{Listen({id})}</div><Portrait id={id} speaking={playing===id} className="adviser-portrait"/>{story&&<Ink text={story.council[id].advice}/>}<p className="lean-note">{story?.council[id].lean==="unsure"?"I would leave this question open for now.":"Gently leaning toward "+(story?.council[id].lean==="A"?input.optionA:input.optionB)}</p></>;}
function leaf(side:"left"|"right",p:Page=page):ReactNode{
if(p==="welcome")return side==="left"?<><span className="chapter-label">A quiet place to begin</span><h1>Every choice<br/><em>has a story.</em></h1><Portrait id="quill" className="intro-portrait"/><p className="portrait-caption">Quill is glad you found your way here.</p></>:<><span className="chapter-label">Welcome, wanderer</span><h2>You don’t have to<br/>think it through alone.</h2><p>In this quiet grove, three small friends see your question in three different ways.</p><div className="council-names"><span><b>Quill</b> considers the practical.</span><span><b>Ember</b> notices what could go wrong.</span><span><b>Willow</b> listens for what matters.</span></div><Button className="ink-button" onClick={()=>go("question")}>Ask your question</Button><button className="text-link sample-link" onClick={demo}>Or read a sample story</button><p className="small-note">AI-written perspectives, for reflection.<br/>The choice stays yours.</p></>;
if(p==="question")return side==="left"?<><span className="chapter-label">Chapter one</span><h1>What is on<br/><em>your mind?</em></h1><p className="question-intro">A fork in the road.<br/>A thought that keeps returning.<br/>Something you’re ready to explore.</p><div className="question-friends"><Portrait id="ember"/><Portrait id="willow"/></div><p className="small-note">A few honest sentences are enough.</p></>:<form onSubmit={e=>{e.preventDefault();void ask();}} className="question-form"><label htmlFor="question">The choice you’re sitting with</label><Textarea id="question" placeholder="I’ve been wondering whether…" maxLength={1800} minLength={8} required value={input.question} onChange={e=>setInput({...input,question:e.target.value})} className="paper-input question-input"/><label htmlFor="option-a"><span>01</span> One possible path</label><Input id="option-a" placeholder="The first option" required minLength={2} maxLength={180} value={input.optionA} onChange={e=>setInput({...input,optionA:e.target.value})} className="paper-input"/><label htmlFor="option-b"><span>02</span> Another possible path</label><Input id="option-b" placeholder="The second option" required minLength={2} maxLength={180} value={input.optionB} onChange={e=>setInput({...input,optionB:e.target.value})} className="paper-input"/>{error&&<p className="form-error" role="alert">{error}</p>}<Button type="submit" className="ink-button ask-button" disabled={turning}>Ask the grove</Button><p className="privacy-note">Your words are sent to Google Gemini for advice and, when you listen, to ElevenLabs for speech. This app doesn’t save your questions.</p><button type="button" className="text-link" onClick={demo}>Read a sample instead</button></form>;
if(p==="gathering")return side==="left"?<><span className="chapter-label">A moment between pages</span><h1>The grove<br/><em>is listening.</em></h1><img className="gathering-scene" src="/art/winter-grove.png" alt="A quiet snowy grove beneath the stars"/><p className="small-note">No need to hurry a thoughtful answer.</p></>:<div className="gathering"><div className="gathering-friends">{characters.map(id=><Portrait key={id} id={id}/>)}</div><h2>Three friends.<br/>Three ways of seeing.</h2><p role="status" aria-live="polite">Considering your question<span className="thinking-dots">…</span></p><blockquote>{input.question}</blockquote><button className="text-link" onClick={()=>{requestRef.current?.abort();go("question");}}>Return to your question</button></div>;
if(p==="council")return AdvicePage({id:side==="left"?"quill":"ember"});
if(p==="willow")return side==="left"?AdvicePage({id:"willow"}):<><span className="chapter-label">Hold all three perspectives</span><h2>A choice can hold<br/>more than one truth.</h2><div className="lean-list">{characters.map(id=><div key={id}><span className={"mini-dot "+id}/><div><h3>{profiles[id].name}<span>{story?.council[id].lean==="unsure"?"Still wondering":story?.council[id].lean==="A"?"Path one":"Path two"}</span></h3><p>{story?.council[id].reason}</p></div></div>)}</div><Button className="ink-button" onClick={()=>go("roots")}>Follow the roots</Button><p className="small-note">Their agreement is a prompt to reflect,<br/>not a measure of what is right.</p></>;
if(p==="keepsake")return side==="left"?<><span className="chapter-label">A page to keep</span><h1>A little clarity<br/><em>to carry with you.</em></h1><p className="keepsake-question">{input.question}</p><div className="keepsake-quotes">{characters.map(id=><div key={id}><Portrait id={id}/><p><b>{profiles[id].name}</b>{story?.council[id].keepsake}</p></div>)}</div></>:<><span className="chapter-label">Begin gently</span><h2>One small<br/>next step.</h2><p className="next-step">{story?.council.next_step}</p><img className="wax-seal" src="/art/wax-seal.png" alt="A teal wax seal with an embossed tree"/><p className="your-choice">This choice is yours.</p><div className="keepsake-actions"><Button className="ink-button" disabled={saving} onClick={async()=>{if(!story)return;setSaving(true);try{setKeepsakeUrl(await downloadKeepsake(input,story));}catch{setError("The keepsake couldn't be saved. Please try again.");}finally{setSaving(false);}}}>{saving?"Preparing your page…":"Save this page"}</Button>{keepsakeUrl&&<a className="text-link" href={keepsakeUrl} download="oracle-grove-keepsake.png">Download your keepsake</a>}<button className="text-link" onClick={restart}>Begin another story</button></div>{error&&<p className="form-error" role="alert">{error}</p>}</>;
if(p==="safety")return side==="left"?<><span className="chapter-label">A moment of care</span><h1>You don’t have to<br/><em>carry this alone.</em></h1><img className="safety-art" src="/art/safety-lantern.png" alt="A warm lantern resting quietly in the snow"/></>:<><span className="chapter-label">Pause here for a moment</span><h2>{generalSafety?"Let’s find a safer way forward.":"Your safety matters more than this choice."}</h2><p>{generalSafety?"The grove can’t weigh up choices that could cause serious harm. Consider reaching out to someone you trust or a qualified professional who can help you think through what is happening.":"If you might hurt yourself or are in immediate danger, contact your local emergency services now. If you can, reach out to someone you trust and ask them to stay with you."}</p>{!generalSafety&&<><p>In the U.S. or Canada, call or text <a href="tel:988">988</a> for crisis support. Elsewhere, find a local service below.</p><a className="ink-button support-link" href="https://findahelpline.com" target="_blank" rel="noreferrer">Find someone to talk to</a></>}<p className="small-note">This storybook cannot provide crisis care.</p><button className="text-link" onClick={restart}>Return to a new question</button><p className="your-choice">This choice is yours.</p></>;
return null;
}
const rich=turning&&!!turnFrom&&!!turnTo&&!compact&&leafW>0&&turnFrom!=="roots"&&turnTo!=="roots"&&turnFrom!=="cover",fwd=turnDir==="forward";
const leftP:Page=rich?(fwd?turnFrom!:turnTo!):page,rightP:Page=rich?(fwd?turnTo!:turnFrom!):page;
const sw=leafW/STRIPS;
const stripTree=(i:number):ReactNode=>{const frontOff=fwd?i*sw:(STRIPS-1-i)*sw,backOff=fwd?(STRIPS-1-i)*sw:i*sw;
const face=(p:Page,side:"left"|"right",off:number)=><div className={"page-"+p} style={{display:"contents"}}><article className={"paper leaf-paper page-"+side} style={{width:leafW,left:-off}}>{leaf(side,p)}</article></div>;
return <div className="strip" key={i} style={{"--sw":sw+"px","--a0":(i/STRIPS)*.34,"--a1":((i+1)/STRIPS)*.34} as CSSProperties}><div className="sf">{face(turnFrom!,fwd?"right":"left",frontOff)}</div><div className="sb">{face(turnTo!,fwd?"left":"right",backOff)}</div>{i<STRIPS-1&&stripTree(i+1)}</div>;};
const next=page==="council"?"willow":page==="roots"?"keepsake":null;
const previous:Partial<Record<Page,Page>>={question:"welcome",council:"question",willow:"council",roots:"willow",keepsake:"roots"};
return <main className={"grove page-"+page} onPointerMove={e=>{const x=e.clientX,y=e.clientY;if(lightRaf.current)return;lightRaf.current=requestAnimationFrame(()=>{lightRaf.current=0;const el=lightRef.current;if(el){el.style.setProperty("--cursor-x",x+"px");el.style.setProperty("--cursor-y",y+"px");}});}}>
<video className="grove-film" autoPlay muted loop playsInline preload="metadata" poster="/art/winter-grove.png"><source src="/art/winter-grove-loop.mp4" type="video/mp4"/></video><div className="night-veil"/><div className="cursor-light" ref={lightRef} aria-hidden/>
<header className="masthead"><a href="/" className="wordmark">✧ <span>ORACLE GROVE</span></a><span className="header-note">A little stillness. A little clarity.</span><Button variant="ghost" className="sound-control" aria-pressed={sound} onClick={soundToggle}>{sound?"◖ Sound on":"◖ Sound off"}</Button><Button variant="ghost" className="sound-control effects-control" aria-pressed={effects} onClick={effectsToggle}>{effects?"♪ Effects on":"♪ Effects off"}</Button><Button variant="ghost" className="sound-control effects-control" aria-pressed={music} onClick={musicToggle}>{music?"♫ Music on":"♫ Music off"}</Button></header>
<div className={"book-stage "+(page!=="cover"?"is-open":"")}>
{page==="cover"?<div className={"arrival "+(opening?"departing":"")}><div className="closed-book"><img src="/art/storybook-cover.png" alt="An old teal storybook with a golden tree and three amber lights"/><div className="cover-lettering"><span>A COUNCIL OF SMALL WONDERS</span><h1>Oracle<br/>Grove</h1><Button className="ink-button" disabled={opening} onClick={()=>{setOpening(true);if(effects){sfx.preload();sfx.open();}if(music)sfx.startAmbient();timers.current.push(setTimeout(()=>{setPage("welcome");setOpening(false);},850));}}>Open the book</Button></div></div><div className="snow-puff" aria-hidden>{Array.from({length:18},(_,i)=><i key={i} style={{"--dx":(i-8)*26+"px","--dy":(-25-(i%5)*17)+"px","--delay":(i%3)*.025+"s"} as CSSProperties}/>)}</div></div>
:<div className="book-with-nav"><div className="chapter-heading" ref={headingRef} tabIndex={-1}><span>{chapters[page]}</span>{story?.sample&&<span className="sample-badge">A sample story</span>}</div><section ref={bookRef} className={"open-book "+(page==="roots"?"night-pages":"")+(turning?" is-turning":"")} aria-label={chapters[page]} aria-busy={page==="gathering"}>{page==="roots"&&story?<Roots story={story} input={input}/>:<><div className={"page-"+leftP} style={{display:"contents"}}><article className="paper page-left">{leaf("left",leftP)}<span className="folio">✧</span></article></div><div className={"page-"+rightP} style={{display:"contents"}}><article className="paper page-right">{leaf("right",rightP)}<span className="folio">✧</span></article></div></>}<span className="spine"/>{turning&&(rich?<div className={"turning-leaf strips "+(fwd?"forward":"back")} aria-hidden>{stripTree(0)}</div>:<div className={"turning-leaf "+(fwd?"forward":"back")} aria-hidden><div className="leaf-front"/><div className="leaf-back"/></div>)}</section>{voiceError&&<p className="voice-error" role="status">{voiceError}</p>}<nav className="book-navigation" aria-label="Story pages"><div>{previous[page]&&<Button variant="ghost" disabled={turning} onClick={()=>go(previous[page]!)}>Previous page</Button>}</div><span className="page-motto">{page==="gathering"?"Some things are worth a quiet moment.":"This choice is yours."}</span><div>{next&&<Button className="ink-button" disabled={turning} onClick={()=>go(next as Page)}>{next==="keepsake"?"Keep a little clarity":"Turn the page"}</Button>}</div></nav></div>}
</div>{page==="cover"&&<p className="arrival-caption">Some choices need a little room to unfold.</p>}<footer className="grove-footer"><span>THREE PERSPECTIVES. YOUR OWN PATH.</span><span>{page==="cover"?"This choice is yours.":"A storybook for reflection"}</span></footer>
</main>;
}
